Default: &defaults
  user: tuto
  password: tuto
  host: localhost
  port: 27017
  database: tuto
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: tuto_test
  <<: *defaults

Staging:
  database: tuto_staging
  poolsize: 100
  <<: *defaults

Production:
  database: tuto_production
  poolsize: 100
  <<: *defaults
